<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage\Success */
$order = $block->getOrder();
$qrcodepix = $order->getPaghiperPix();
$boleto = $order->getPaghiperBoleto();
$linha_digitavel = $order->getPaghiperBoletoDigitavel();
$chavepix = $order->getPaghiperChavepix();
$payment = $order->getPayment();
?>
<?php if ($payment->getMethod() === 'paghiper_pix') : ?>
  <div class="actions-toolbar flex">
    <div class="primary">
      <img src="<?= /* @noEscape */ $qrcodepix ?>" />
    </div>
    <div class="linhes">
      <h3> <?php echo __('Digitable line'); ?></h3>
      <textarea readonly rows="5" name="pixer" id="select-this"><?= /* @noEscape */ $chavepix ?></textarea>
      <div class="actions-toolbar">
        <div class="primary">
          <button id='clickMe'><?php echo __('Copy'); ?></button>
        </div>
      </div>
    </div>
  </div>
<?php endif ?>
<?php if ($payment->getMethod() === 'paghiper_boleto') : ?>
  <div class="actions-toolbar flex">
    <div class="linhes">
      <h3><?php echo __('Digitable line'); ?></h3>
      <div class="flex">
        <textarea readonly rows="1" name="pixer" id="select-this"><?= /* @noEscape */ $linha_digitavel ?></textarea>
        <div class="actions-toolbar linha-digitavel">
          <div class="primary">
            <button id='clickMe'><?php echo __('Copy'); ?></button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="view-boleto">
    <iframe src="<?= /* @noEscape */ $boleto ?>" width="100%" height="500px">
    </iframe>
  </div>
  <div class="primary">
    <a target="_blank" class="action primary continue" href="<?= /* @noEscape */ $boleto ?>">
      <span><?php echo __('View Billet'); ?></span>
    </a>
  </div>
<?php endif ?>