<?php
$paymentInfo = $block->getPaymentInfo();

if ($block->getPaymentMethod() === 'paghiper_boleto') : ?>

  <button type="button" class="action primary btn-paghiper-pix" data-trigger="trigger">
    <span data-bind="i18n: '<?= $block->escapeJs($paymentInfo['texto']); ?>'"></span>
  </button>

  <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalpix',
            'title': 'Boleto',
            'trigger': '[data-trigger=trigger]',
            'responsive': true
        }}">
    <div class="content">
      <input
        class="action primary btn-paghiper-boleto"
        type="button"
        id="paghiper"
        onclick="window.open('<?= $block->escapeHtmlAttr($paymentInfo['url']); ?>');"
        value="<?= $block->escapeHtmlAttr(__('Baixe seu boleto aqui')); ?>" />
    </div>

    <h3><?= $block->escapeHtml(__('Digitable line')); ?></h3>

    <textarea readonly rows="1" name="pixer" id="select-this">
      <?= $block->escapeHtml($paymentInfo['linha-digitavel']); ?>
    </textarea>

    <div class="actions-toolbar">
      <div class="primary">
        <button id="clickMe">
          <?= $block->escapeHtml(__('Copy')); ?>
        </button>
      </div>
    </div>
  </div>

<?php
elseif ($block->getPaymentMethod() === 'paghiper_pix') : ?>

  <button type="button" class="action primary btn-paghiper-pix" data-trigger="trigger">
    <span data-bind="i18n: '<?= $block->escapeJs($paymentInfo['texto']); ?>'"></span>
  </button>

  <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalpix',
            'title': 'Escaneie o QRcode',
            'trigger': '[data-trigger=trigger]',
            'responsive': true
        }}">
    <div class="content">
      <img
        src="<?= $block->escapeHtmlAttr($paymentInfo['url']); ?>"
        alt="<?= $block->escapeHtmlAttr(__('Erro ao carregar seu QRCode')); ?>">
    </div>

    <h3><?= $block->escapeHtml(__('Digitable line')); ?></h3>

    <textarea readonly rows="5" name="pixer" id="select-this">
      <?= $block->escapeHtml($paymentInfo['chavepix']); ?>
    </textarea>

    <div class="actions-toolbar">
      <div class="primary">
        <button id="clickMe">
          <?= $block->escapeHtml(__('Copy')); ?>
        </button>
      </div>
    </div>
  </div>

<?php endif; ?>
